### ISSUE TITLE
Can replay under Windows?

### ISSUE THREAD

**Issue by stjeong** [JohnDMcMaster/usbrply#30]
I didn't see any words about that. Can replay on Windows?

**Comment by JohnDMcMaster** [comment]
Hi! Thanks for reaching out. usbrply probably runs on Widows, but as I'm not a Windows user and do not know much about Python there I cannot comment. If you try things though, I'd love to hear feedback and/or instructions.

**Comment by kafisatz** [comment]
Hi there.
I wanted to try this under windows.

It is not clear to me how I should run this step 'Linux: run: "usbrply --device-hi -p my.pcapng >replay.py"'
can you elaborate please?

**Comment by JohnDMcMaster** [comment]
Hi kafisatz,
Unfortunately there haven't been any major changes since my previous comment. I'm not a Windows person and haven't had time to research this. Current effort will be put into fixing some of the bugs affecting the framework in general. Some of this may include things like upgrading the packet library / Python3 which may be required for Windows anyway.

**Comment by JohnDMcMaster** [comment]
I've cut a pip release and added Windows instructions (see latest README). Probably could be more streamlined but this should work. Please let me know if you run into any issues
